export const FETCHING_COFFEE = "FETCHING_COFFEE";
export const FETCHING_COFFEE_SUCCESS = "FETCHING_COFFEE_SUCCESS";
export const FETCHING_COFFEE_FAILURE = "FETCHING_COFFEE_FAILURE";
export const FETCHING_COFFEEMAKER = "FETCHING_COFFEEMAKER";
export const FETCHING_COFFEEMAKER_SUCCESS = "FETCHING_COFFEEMAKER_SUCCESS";
export const FETCHING_COFFEEMAKER_FAILURE = "FETCHING_COFFEEMAKER_FAILURE";
